
model:
  main:
    checkpoint: /aicenter2/mol_generation/ckpts/TDSBDD/main_model.pt
  frontier:
    checkpoint: /aicenter2/mol_generation/ckpts/TDSBDD/frontier_model.pt

sample:
  seed: 100
  num_samples: 100
  beam_size: 300
  logp_thres: -.inf
  num_retry: 5
  max_steps: 50
